[package]
name = "bourso_api"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["multipart", "cookies"] }
anyhow = { version = "1.0.75" }
regex = { version = "1.10.2" }
lazy_static = { version = "1.4.0" }
clap = { version = "4.4.6", features = ["derive"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = { version = "1.0.107" }
reqwest_cookie_store = "0.6.0"
cookie_store = "0.20.0"
chrono = { version = "0.4.31" }
log = { version = "0.4.20" }